### ISSUE TITLE
question: Upsampler (238M)

### ISSUE THREAD

**Issue by playdasegunda** [flavioschneider/master-thesis#1]
Could you please share the code for the "Upsampler (238M)" model, which you found at this [link](https://flavioschneider.notion.site/flavioschneider/Audio-Generation-with-Diffusion-c4f29f39048d4f03a23da13078a44cdb#41b984b50eaf4b1a9b953f1ff892e278), so that we can "upsample" a low-quality audio file using a repository, such as huggingface or colab? 

Thank you, Lucas Rodrigues.

**Comment by flavioschneider** [comment]
The code for the upsampler can be found here [github.com/archinet/audio-diffusion-pytorch](github.com/archinet/audio-diffusion-pytorch), the config is the following:
```yaml
    in_channels: 2
    upsample_factor: 16
    channels: [8, 32, 64, 128, 256, 512, 512, 1024, 1024]
    factors: [1, 4, 4, 4, 2, 2, 2, 2, 2]
    items: [1, 2, 2, 2, 2, 2, 2, 4, 4]
    attentions: [0, 0, 0, 0, 0, 1, 1, 1, 1]
    attention_heads: 12
    attention_features: 64
```

You have to train your own for now, I might release a pretrained version in the future.
